### ISSUE TITLE
StatusLogger Log4j2 could not find a logging implementation.

### ISSUE THREAD

**Issue by radostnomne** [freshollie/jest-dynalite#14]
Hi. Im trying to use your library according documentation. Im using typescript.
```js
// jest.config.js
module.exports = {
  preset: '@shelf/jest-dynamodb',
  roots: ['<rootDir>'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
  },
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  setupFiles: ['dotenv/config'],
};
```
and
```js
// jest-dynamodb-config.js
module.exports = {
  tables: [
    {
      TableName: 'users',
      KeySchema: [{ AttributeName: 'id', KeyType: 'HASH' }],
      AttributeDefinitions: [{ AttributeName: 'id', AttributeType: 'S' }],
      ProvisionedThroughput: {
        ReadCapacityUnits: 1,
        WriteCapacityUnits: 1,
      },
    },
  ],
  basePort: 8888,
};
```

command to run tests: `npm run test` , where "test": "jest --silent"
I am getting the error:
`Determining test suites to run...ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/ServletInputStream
        at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServer(ServerRunner.java:120)
        at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.createServerFromCommandLineArgs(ServerRunner.java:116)
        at com.amazonaws.services.dynamodbv2.local.main.ServerRunner.main(ServerRunner.java:71)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletInputStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more
Error: connect ECONNREFUSED 127.0.0.1:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)`

How to solve this?

**Comment by freshollie** [comment]
Looks like you are using `jest-dynamodb` not `jest-dyanlite`. Your jest config should use `jest-dynalite` as the `preset` and `jest-dynalite-config.js` as your dynalite config.

**Comment by freshollie** [comment]
FYI, I know this because your error output is java based, which `jest-dynalite` doesn't use.

**Comment by radostnomne** [comment]
thanks.

**Comment by freshollie** [comment]
In my opinion jest-dyanlite is better to use, and is a drop in replacement. Consider using it ;)
