### ISSUE TITLE
ReadError: Database is not open / existing setup after env

### ISSUE THREAD

**Issue by Mattensor** [freshollie/jest-dynalite#67]
Hey there 

I get the following error when running dynalite.

```
ReadError: Database is not open
    at /api/node_modules/levelup/lib/levelup.js:190:15
    at /api/node_modules/encoding-down/index.js:75:21
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

I have an existing setupFilesAfterEnv file in which there are conflicts.
When I remove it, my tests work - but I have no dynalite goodness :(

afterEnvSetup
```
import { server } from '~mocks/server'

beforeAll(() => {
  server.listen({
    onUnhandledRequest: 'warn'
  })
})

afterAll(() => {
  server.close()
})

afterEach(() => {
  server.resetHandlers()
})

```

I've tried the granular approach importing the start / stop fns individually. The out of the box solution and on an individual file. Still no luck

Would be great to get some help

**Comment by jonoirwinrsa** [comment]
I had this issue too - for me it was because I had undefined TableName being returned in my jest-dynalite-config.js file. Perhaps it's the same for you?

**Comment by Mattensor** [comment]
It works if I remove my other afterEnvSetup setup file, but I need that to setup to mock external api calls.

Here's my jest-dynalite-config.ts file

```
const tables = [
  {
    TableName: 'conversations',
    AttributeDefinitions: [
      { AttributeName: 'id', AttributeType: 'S' },
      { AttributeName: 'userId', AttributeType: 'S' }
    ],
    KeySchema: [{ AttributeName: 'id', KeyType: 'HASH' }],
    BillingMode: 'PAY_PER_REQUEST',
    GlobalSecondaryIndexes: [
      {
        IndexName: 'userConversationsIndex',
        KeySchema: [{ AttributeName: 'userId', KeyType: 'HASH' }],
        Projection: { ProjectionType: 'ALL' }
      }
    ]
  }
]

module.exports = {
  tables,
  basePort: 8000
}
```

**Comment by freshollie** [comment]
Ok. Can you narrow down which test is causing this error and maybe post details about this test? It's likely you get an error like this if a DB call happens outside a test (as this library tears down the server after each test)

**Comment by yamatatsu** [comment]
I've created a minimal representation code.

https://github.com/yamatatsu/represent-jest-dynalite-database-is-not-open

I guess the condition of this error is below:

- many commands to db have been queued to node event-loop
- timeout the test case

In my case, the work arround I found is to extend the timeout period.
```ts
test('test case' async () => {...}, 60_000 /* long enough */)
```
