### ISSUE TITLE
AWS SDK error wrapper for Error: Parse Error: Expected HTTP/

### ISSUE THREAD

**Issue by cgreening** [freshollie/jest-dynalite#71]
I've suddenly started receiving this error - any ideas what is triggering it?

```
    AWS SDK error wrapper for Error: Parse Error: Expected HTTP/

      at asSdkError (node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:124:10)
      at StandardRetryStrategy.retry (node_modules/@aws-sdk/middleware-retry/src/StandardRetryStrategy.ts:94:21)
      at node_modules/@aws-sdk/middleware-logger/src/loggerMiddleware.ts:22:22
          at async Promise.all (index 0)
      at node_modules/jest-dynalite/src/dynamodb/v3.ts:96:5
      at Object.createTables (node_modules/jest-dynalite/src/db.ts:51:5)
      at Object.<anonymous> (node_modules/jest-dynalite/src/clearAfterEach.ts:5:3)
```

**Comment by freshollie** [comment]
Damn, that's interesting, not sure why that would be. What version of `@aws-sdk/client-dynamodb` are you using?

**Comment by cgreening** [comment]
What's weird is it's just started happening - I'll try and create something reproducible.

```
"@aws-sdk/client-dynamodb": "^3.28.0"
```

**Comment by freshollie** [comment]
What's the version in the lock file?

**Comment by cgreening** [comment]
```
"@aws-sdk/client-dynamodb@^3.28.0":
  version "3.28.0"
  resolved "https://registry.yarnpkg.com/@aws-sdk/client-dynamodb/-/client-dynamodb-3.28.0.tgz#4a827de289b5fa048b4e646c480582fb8e201ad1"
  integrity sha512-RkjvHUk+rCC7v28/TVMgVT2KvPOchhW0pM2O0VApPJ5CG6NvyNB+vY/NiEl5NMMuwQQ1mmKbqMPBKEjtSIwH1A==
  dependencies:
    "@aws-crypto/sha256-browser" "^1.0.0"
    "@aws-crypto/sha256-js" "^1.0.0"
    "@aws-sdk/client-sts" "3.28.0"
    "@aws-sdk/config-resolver" "3.28.0"
    "@aws-sdk/credential-provider-node" "3.28.0"
    "@aws-sdk/fetch-http-handler" "3.25.0"
    "@aws-sdk/hash-node" "3.25.0"
    "@aws-sdk/invalid-dependency" "3.25.0"
    "@aws-sdk/middleware-content-length" "3.25.0"
    "@aws-sdk/middleware-endpoint-discovery" "3.28.0"
    "@aws-sdk/middleware-host-header" "3.25.0"
    "@aws-sdk/middleware-logger" "3.25.0"
    "@aws-sdk/middleware-retry" "3.28.0"
    "@aws-sdk/middleware-serde" "3.25.0"
    "@aws-sdk/middleware-signing" "3.28.0"
    "@aws-sdk/middleware-stack" "3.25.0"
    "@aws-sdk/middleware-user-agent" "3.25.0"
    "@aws-sdk/node-config-provider" "3.28.0"
    "@aws-sdk/node-http-handler" "3.25.0"
    "@aws-sdk/protocol-http" "3.25.0"
    "@aws-sdk/smithy-client" "3.28.0"
    "@aws-sdk/types" "3.25.0"
    "@aws-sdk/url-parser" "3.25.0"
    "@aws-sdk/util-base64-browser" "3.23.0"
    "@aws-sdk/util-base64-node" "3.23.0"
    "@aws-sdk/util-body-length-browser" "3.23.0"
    "@aws-sdk/util-body-length-node" "3.23.0"
    "@aws-sdk/util-user-agent-browser" "3.25.0"
    "@aws-sdk/util-user-agent-node" "3.28.0"
    "@aws-sdk/util-utf8-browser" "3.23.0"
    "@aws-sdk/util-utf8-node" "3.23.0"
    "@aws-sdk/util-waiter" "3.25.0"
    tslib "^2.3.0"
    uuid "^8.3.2"
```

**Comment by freshollie** [comment]
Hmm, I also can't reproduce locally with `@aws-sdk/client-dynamodb@^3.28.0`

Your lock file has definitely not changed? When was the last stable version in CI?

**Comment by cgreening** [comment]
Just checked with a colleague and it's working on his machine - and it works on our build machine - so something has gone wonky with my machine...

Is there anything outside of the node_modules that can influence things?

**Comment by freshollie** [comment]
Have you got anything running on the same port as the dynalite servers? Your `basePort` + number of runners so `8000, 8001, 8002, 8003` for example

**Comment by freshollie** [comment]
MacOS sometimes lets you run more than 1 server on the same port

**Comment by cgreening** [comment]
You sir are a lifesaver - something was running on the port and messing things up! All fixed and working again.
