### ISSUE TITLE
 InvalidClientTokenId: The security token included in the request is invalid

### ISSUE THREAD

**Issue by Rory-Powell** [freshollie/jest-dynalite#80]
Hi tere, 

I'm having a problem using dynalite for write requests. I'm able to start the database using
```js
import { startDb, stopDb, createTables, deleteTables } from "jest-dynalite";

export const start = async () => {
  await startDb()
  await createTables()
}

export const stop = async () => {
  await deleteTables()
  await stopDb()
}

```

which is wired into my `beforeAll` via another central test config. 

alongside my setup file that is used by `setupFiles: [ "./src/tests/setup/jest/setup.ts" ],` 
```js
// test dynamo
import { setup } from "jest-dynalite";
setup("./");
env._set("DYNAMODB_URL", process.env.MOCK_DYNAMODB_ENDPOINT)
env._set("DYNAMODB_REGION", "us-east-1")
env._set("ACCOUNT_DYNAMODB_TABLE", "test-budi-accounts")
```

which is applied to the dynamo client:
```js
    const dynamoConfig: ClientConfiguration = {
      apiVersion: "2012-08-10",
    }

    if (env.DYNAMODB_URL) {
      dynamoConfig.endpoint = env.DYNAMODB_URL
    }

    if (env.isTest()) {
      dynamoConfig.sslEnabled = false
    }

    if (env.DYNAMODB_REGION) {
      dynamoConfig.region = env.DYNAMODB_REGION
    }

    this.client = new DocumentClient(dynamoConfig)
```

however when I try to do a write operation I am seeing:
```
    InvalidClientTokenId: The security token included in the request is invalid.

      at Request.extractError (node_modules/aws-sdk/lib/protocol/query.js:50:29)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (node_modules/aws-sdk/lib/request.js:686:14)
      at Request.transition (node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (node_modules/aws-sdk/lib/state_machine.js:14:12)
      at node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (node_modules/aws-sdk/lib/request.js:688:12)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:116:18)
```
I am using version `2.980.0` of aws-sdk, but I also see this on the latest `2.1107.0`

Am I doing anything wrong?

**Comment by Rory-Powell** [comment]
Closing this - the error wasn't being thrown by dynamo, but by SES which sends an email right after my dynamo insert
