### ISSUE TITLE
 AWS SDK error wrapper for Error: connect ECONNREFUSED 127.0.0.1:6001

### ISSUE THREAD

**Issue by vladimirgal1012** [freshollie/jest-dynalite#85]
Hi folks,

I am trying to get dynalite working with base setup but for some reason it looks like I cannot disable tls for some reason.

My current setup is:

jest-dynalite-config.ts
```ts
module.exports = {
	tables: [
		{
			TableName: 'api-test',
			KeySchema: [
				{ AttributeName: 'id', KeyType: 'HASH' },
				{ AttributeName: 'entity', KeyType: 'RANGE' },
			],
			AttributeDefinitions: [
				{ AttributeName: 'id', AttributeType: 'S' },
				{ AttributeName: 'entity', AttributeType: 'S' },
			],
			ProvisionedThroughput: { ReadCapacityUnits: 1, WriteCapacityUnits: 1 },
		},
	],
	basePort: 6000,
}
```

then client:
```
new DynamoDBClient({
				credentials: {
					accessKeyId: 'dummytest',
					secretAccessKey: 'dummytest',
				},
				endpoint: process.env.MOCK_DYNAMODB_ENDPOINT,
				region: 'local',
				tls: false,
})
```

When I try to run any basic test it throws an error which looks like it is trying to connect to ssl endpoint, not htttp:

```
AWS SDK error wrapper for Error: connect ECONNREFUSED 127.0.0.1:6001

      at asSdkError (node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:103:12)
      at StandardRetryStrategy.retry (node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:61:29)
      at async /home/mrdreix/projects/spg/funcard-node/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
          at async Promise.all (index 0)
      at async /home/mrdreix/projects/spg/funcard-node/node_modules/jest-dynalite/src/dynamodb/v3.ts:96:5
      at async createTables (node_modules/jest-dynalite/src/db.ts:51:5)
      at async Object.<anonymous> (node_modules/jest-dynalite/src/clearAfterEach.ts:5:3)
```

Versions:
jest-dynalite@npm:3.6.1 [0460f] (via npm:^3.6.1 [0460f])
@aws-sdk/client-dynamodb@npm:3.172.0 (via npm:^3.172.0)

Thanks for any help or suggestion

**Comment by vladimirgal1012** [comment]
Fixed.

For any future comers, this was related to https://github.com/freshollie/jest-dynalite/issues/9.

I just removed `testEnvironment: 'node'` from jest.config.ts and everything started working.
